apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 82
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 100m # TODO: Set this to the maximum amount of CPU you want your workload to use
              memory: 512Mi # TODO: Set this to the maximum amount of memory you want your workload to use
            requests:
              cpu: 100m # TODO: Set this to the amount of CPU you want to reserve for your workload
              memory: 512Mi # TODO: Set this to the amount of Memory you want to reserve for your workload
          imagePullPolicy: Always
          readinessProbe:
            # TODO: Change the readinessProbe setting to reflect your application's readiness to serve traffic
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            # TODO: Change the livenessProbe setting to reflect your application's health
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
