checks:
  polaris:
    runAsRootAllowed:
      severity: medium
    livenessProbeMissing:
      severity: high
      ci:
        block: true
      admission:
        block: false
    labelMissing:
      severity: high
  opa:
    labelMissing: high        